### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by tanlili2025** [gaoyh111/MeterDetection#2]
您好，我没有极市仪表数据集，我在网上找的数据集有些只有标注表盘的，有些标注指针的，我可以用不同的数据集分别对三个部分（表盘，指针2个关键点，数值框）进行训练，生成3个训练模型，然后用你的检测代码进行真实的仪表读数检测吗？谢谢！

**Comment by gaoyh111** [comment]
可以的，通过模型定位到刻度值位置后，还需要ocr识别刻度值，这里采用的mmocr，你也可以选择其他方式进行ocr识别

**Comment by tanlili2025** [comment]
> 可以的，通过模型定位到刻度值位置后，还需要ocr识别刻度值，这里采用的mmocr，你也可以选择其他方式进行ocr识别

谢谢，
1.对于刻度值识别，有些表有5个刻度值，有些有6或者7个，这个需要区分吗？
2.指针识别，我用的识别仪表指针两个端点，我看你画的是矩形框，和你的通用吗？
3.另外你的最终检测识别代码支持一个图里有2个或者以上的表吗？

**Comment by gaoyh111** [comment]
> > 可以的，通过模型定位到刻度值位置后，还需要ocr识别刻度值，这里采用的mmocr，你也可以选择其他方式进行ocr识别
> 
> 谢谢， 1.对于刻度值识别，有些表有5个刻度值，有些有6或者7个，这个需要区分吗？ 2.指针识别，我用的识别仪表指针两个端点，我看你画的是矩形框，和你的通用吗？ 3.另外你的最终检测识别代码支持一个图里有2个或者以上的表吗？

1、不需要区分
2、可以用两个端点创造一个矩形目标框。yolov8需要一个目标框和2个关键点。
3、应该支持

**Comment by tanlili2025** [comment]
我现在使用的是两个矩形框训练指针识别的，仪表中心是一个矩形框，指针头是一个矩形框，这样是不是和你的方法【一个矩形框，两个关键点】不一致了？

**Comment by tanlili2025** [comment]
> > > 可以的，通过模型定位到刻度值位置后，还需要ocr识别刻度值，这里采用的mmocr，你也可以选择其他方式进行ocr识别
> > 
> > 
> > 谢谢， 1.对于刻度值识别，有些表有5个刻度值，有些有6或者7个，这个需要区分吗？ 2.指针识别，我用的识别仪表指针两个端点，我看你画的是矩形框，和你的通用吗？ 3.另外你的最终检测识别代码支持一个图里有2个或者以上的表吗？
> 
> 1、不需要区分 2、可以用两个端点创造一个矩形目标框。yolov8需要一个目标框和2个关键点。 3、应该支持

我现在使用的是两个矩形框训练指针识别的，仪表中心是一个矩形框，指针头是一个矩形框，这样是不是和你的方法【一个矩形框，两个关键点】不一致了？

**Comment by gaoyh111** [comment]
> > > > 可以的，通过模型定位到刻度值位置后，还需要ocr识别刻度值，这里采用的mmocr，你也可以选择其他方式进行ocr识别
> > > 
> > > 
> > > 谢谢， 1.对于刻度值识别，有些表有5个刻度值，有些有6或者7个，这个需要区分吗？ 2.指针识别，我用的识别仪表指针两个端点，我看你画的是矩形框，和你的通用吗？ 3.另外你的最终检测识别代码支持一个图里有2个或者以上的表吗？
> > 
> > 
> > 1、不需要区分 2、可以用两个端点创造一个矩形目标框。yolov8需要一个目标框和2个关键点。 3、应该支持
> 
> 我现在使用的是两个矩形框训练指针识别的，仪表中心是一个矩形框，指针头是一个矩形框，这样是不是和你的方法【一个矩形框，两个关键点】不一致了？

嗯，不一致也没关系，目的都是为了检测出指针的两个端点，使用的时候照你的方法稍微修改一下就行了。

**Comment by tanlili2025** [comment]
> > > > > 可以的，通过模型定位到刻度值位置后，还需要ocr识别刻度值，这里采用的mmocr，你也可以选择其他方式进行ocr识别
> > > > 
> > > > 
> > > > 谢谢， 1.对于刻度值识别，有些表有5个刻度值，有些有6或者7个，这个需要区分吗？ 2.指针识别，我用的识别仪表指针两个端点，我看你画的是矩形框，和你的通用吗？ 3.另外你的最终检测识别代码支持一个图里有2个或者以上的表吗？
> > > 
> > > 
> > > 1、不需要区分 2、可以用两个端点创造一个矩形目标框。yolov8需要一个目标框和2个关键点。 3、应该支持
> > 
> > 
> > 我现在使用的是两个矩形框训练指针识别的，仪表中心是一个矩形框，指针头是一个矩形框，这样是不是和你的方法【一个矩形框，两个关键点】不一致了？
> 
> 嗯，不一致也没关系，目的都是为了检测出指针的两个端点，使用的时候照你的方法稍微修改一下就行了。

1.这个是要改你检测的代码吗？如果按照你的方法，用一个框，另外两个关键点信息放在哪里呢？
2.mmocr使用时是否需要预训练呢？

**Comment by gaoyh111** [comment]
> > > > > > 可以的，通过模型定位到刻度值位置后，还需要ocr识别刻度值，这里采用的mmocr，你也可以选择其他方式进行ocr识别
> > > > > 
> > > > > 
> > > > > 谢谢， 1.对于刻度值识别，有些表有5个刻度值，有些有6或者7个，这个需要区分吗？ 2.指针识别，我用的识别仪表指针两个端点，我看你画的是矩形框，和你的通用吗？ 3.另外你的最终检测识别代码支持一个图里有2个或者以上的表吗？
> > > > 
> > > > 
> > > > 1、不需要区分 2、可以用两个端点创造一个矩形目标框。yolov8需要一个目标框和2个关键点。 3、应该支持
> > > 
> > > 
> > > 我现在使用的是两个矩形框训练指针识别的，仪表中心是一个矩形框，指针头是一个矩形框，这样是不是和你的方法【一个矩形框，两个关键点】不一致了？
> > 
> > 
> > 嗯，不一致也没关系，目的都是为了检测出指针的两个端点，使用的时候照你的方法稍微修改一下就行了。
> 
> 1.这个是要改你检测的代码吗？如果按照你的方法，用一个框，另外两个关键点信息放在哪里呢？ 2.mmocr使用时是否需要预训练呢？
1、用你的方法，那1500行那边就要导入你的代码，并且按你的方式来获取关键点。如果你想跑通，起码代码里怎么调用模型你要搞懂。
yolo pose一个目标框可以携带任意个关键点，我这里携带了两个；目标框是把指针的这两个关键点作为对角点生成的矩形，如果生成矩形过小，微调一下。
2、mmocr可以直接使用他们调参好的，因为只是识别一些数字，完全够用。也可以训练，相同数据集的数字能识别的更准确。

**Comment by tanlili2025** [comment]
@gaoyh111 谢谢，我对yolov8确实不太熟悉，我换一个数据集和你的原版构想保持一致。

**Comment by tanlili2025** [comment]
@gaoyh111 您好，在制作刻度数据集和指针数据集的时候，需要把指针指示的真实值标注到到数据集进行训练吗？

**Comment by gaoyh111** [comment]
> @gaoyh111 您好，在制作刻度数据集和指针数据集的时候，需要把指针指示的真实值标注到到数据集进行训练吗？

不需要啊，读数是根据模型得到的指针端点和刻度点 算出来的

**Comment by tanlili2025** [comment]
@gaoyh111 好的，谢谢，我是看到极市官方数据集介绍带了这个信息。刻度点信息里只有主要的刻度比如【0，0.4，0.8，1.2，1.6】，但是每两个刻度点之间还有刻度线（这个应该没有放到数据集训练吧？），但是没有对应的数值，这个时候模型是怎么计算的呢？

**Comment by gaoyh111** [comment]
> @gaoyh111 好的，谢谢，我是看到极市官方数据集介绍带了这个信息。刻度点信息里只有主要的刻度比如【0，0.4，0.8，1.2，1.6】，但是每两个刻度点之间还有刻度线（这个应该没有放到数据集训练吧？），但是没有对应的数值，这个时候模型是怎么计算的呢？
建议你仔细看一下我的ppt，流程里计算读数是用指针与刻度点的夹角推算出来的，不需要小刻度线

**Comment by tanlili2025** [comment]
@gaoyh111 好的，我看你的ppt上面只有主要的带数字的刻度线。我有个问题，极市的数据集里的表从起点到终点都是270度吗？实际使用的时候如果超过270度，小于360度，是不是进行适应性修改就可以了?

**Comment by gaoyh111** [comment]
不太行，

> @gaoyh111 好的，我看你的ppt上面只有主要的带数字的刻度线。我有个问题，极市的数据集里的表从起点到终点都是270度吗？实际使用的时候如果超过270度，小于360度，是不是进行适应性修改就可以了?

不太行，我这里是基于量程不超过270度去调整仪表的顺序的（仪表倒置，旋转能够矫正），如果小于270°好说，如果量程大于270°，代码得重构

**Comment by tanlili2025** [comment]
@gaoyh111 您的冠军方案，实际探测的结果准确率有多少呢？

**Comment by gaoyh111** [comment]
> @gaoyh111 您的冠军方案，实际探测的结果准确率有多少呢？

89.几，准度是肯定有的，而且高了第二名6个点

**Comment by tanlili2025** [comment]
@gaoyh111 
1.我正在用labelme标注指针和两个关键点。实际选用的图片是带有实际背景的仪表或只有一个仪表的去训练模型呢？
2.实际标注的偏差比如1个像素点对最终训练的效果有多大影响呢？
3.实际照片越清晰是不是识别的准确率要更好点呢？

**Comment by gaoyh111** [comment]
> @gaoyh111 1.我正在用labelme标注指针和两个关键点。实际选用的图片是带有实际背景的仪表或只有一个仪表的去训练模型呢？ 2.实际标注的偏差比如1个像素点对最终训练的效果有多大影响呢？ 3.实际照片越清晰是不是识别的准确率要更好点呢？
1、检测仪表，需要有实际背景，后续指针刻度点检测只需要仪表大图即可
2、微乎其微，标注的时候人眼感觉准就行了
3、照片只要不是很模糊就行，yolo默认图片是640*640

**Comment by tanlili2025** [comment]
@gaoyh111 好的，我目前用yolov5训练了仪表检测，您之前说用yolov8-pose训练指针和刻度点识别时，300个数据集大概能训练成什么效果呢？或者说您比赛时训练的效果是多少，才有最后的90%准确率呢。

**Comment by gaoyh111** [comment]
> @gaoyh111 好的，我目前用yolov5训练了仪表检测，您之前说用yolov8-pose训练指针和刻度点识别时，300个数据集大概能训练成什么效果呢？或者说您比赛时训练的效果是多少，才有最后的90%准确率呢。
300大差不差，就是指针刻度点模型识别的不是很准，比赛用了3000张图训得模型很准，基本1000张就够了如果仪表就一种几百张也够了

**Comment by tanlili2025** [comment]
@gaoyh111 我的目标检测仪表大概有几种，小1000张照片。里面有一个仪表（电接点压力表）比较奇怪，是有3根针，指针和上下限的针，上下限的针（绿色红色）和指针（黑色）颜色不同。这种仪表yolo是不是就束手无策了？或者加入颜色属性？

**Comment by gaoyh111** [comment]
我的代码肯定不适用，你需要修改

**Comment by tanlili2025** [comment]
@gaoyh111 我先实现其他普通类型的仪表吧，这个我先忽略。谢谢您！

**Comment by tanlili2025** [comment]
@gaoyh111 对了，请问指针和刻度训练的时候是尽量选择不同的仪表制作数据集吗？

**Comment by gaoyh111** [comment]
使用什么仪表，就用什么仪表训练

**Comment by tanlili2025** [comment]
@gaoyh111 也就是选用和探测仪表相同的表，实际指示不同的值，反复训练吗？

**Comment by gaoyh111** [comment]
嗯

**Comment by tanlili2025** [comment]
@gaoyh111您好，请问在进行指针训练时，yolov8-pose.yaml里的backone和head里的参数需要修改或者注释掉吗？

**Comment by gaoyh111** [comment]
--------------原始邮件--------------
发件人："tanlili2025 ***@***.***&gt;;
发送时间：2024年8月11日(星期天) 下午5:59
收件人："gaoyh111/MeterDetection" ***@***.***&gt;;
抄送："gaoyh111 ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [gaoyh111/MeterDetection] 数据集问题 (Issue #2)
-----------------------------------

 

 
@gaoyh111您好，请问在进行指针训练时，yolov8-pose.yaml里的backone和head里的参数需要修改或者注释掉吗？
 
不需要—

**Comment by tanlili2025** [comment]
@gaoyh111 好的，谢谢，那我就不动这里。那coco-pose.yaml里的flip_idx:原来是有0-16的值，我这里用了两个关键点，所以改成这样【0，1】可以吗？

**Comment by gaoyh111** [comment]
> @gaoyh111 好的，谢谢，那我就不动这里。那coco-pose.yaml里的flip_idx:原来是有0-16的值，我这里用了两个关键点，所以改成这样【0，1】可以吗？

不清楚了，好像没改过这里，你看看网上的例子吧

**Comment by tanlili2025** [comment]
@gaoyh111  谢谢，我看网上说如果关键点是对称的这里就要修改，有一个人21个关键点，这里就在列表里加了17-20。我手工标注了638个，80%用作训练。请问你之前指针执行了多少轮训练啊？

**Comment by gaoyh111** [comment]
建议你参考网上的例子，收敛就可以了，先跑个100轮看看

**Comment by tanlili2025** [comment]
@gaoyh111 好的，我正在跑100轮，请问您在ppt里写的刻度关键点权重修改，是改的default.yaml中的pose吗？还是别的地方的文件呢？

**Comment by gaoyh111** [comment]
命令行参数

**Comment by tanlili2025** [comment]
@gaoyh111 😓，我看了yolov8的41个训练参数，没找到，您在命令行修改的是哪一个呢？

**Comment by gaoyh111** [comment]
https://docs.ultralytics.com/modes/train/#resuming-interrupted-trainings
<html>
<body>

pose | 12.0 | Weight of the pose loss in models trained for pose estimation, influencing the emphasis on accurately predicting pose keypoints.
-- | -- | --



</body>
</html>

**Comment by tanlili2025** [comment]
@gaoyh111 哦哦，好的，刚才看到这个pose不敢确定，只有这个默认值是12。

**Comment by tanlili2025** [comment]
[results0811.csv](https://github.com/user-attachments/files/16573652/results0811.csv)
@gaoyh111 您好，这是训练了100轮的结果，用了510个图片，请问这个结果是训练集少了还是训练量少了呢？

**Comment by gaoyh111** [comment]
你自己判断吧，自己测试效果，不要总问我啊
![0F724267](https://github.com/user-attachments/assets/cc3179d9-094d-483a-a6a4-75f52b2dd4fb)

**Comment by tanlili2025** [comment]
@gaoyh111 好的好的。打扰了哈

**Comment by tanlili2025** [comment]
@gaoyh111  您好，我在制作仪表刻度数据集，有一张图片两个仪表，这两个仪表可以标注在一个文件训练还是要把仪表截出来，每一个仪表对应一个单独的标注文件？

**Comment by gaoyh111** [comment]
这个是yolO相关的问题吧，yolo标注在一个文件就可以，下次你可以去yolo社区问 ，我最近比较忙，而且我贴了代码不是包教包会的，还得靠你自己（抱拳）

--------------原始邮件--------------
发件人："tanlili2025 ***@***.***&gt;;
发送时间：2024年8月12日(星期一) 中午12:42
收件人："gaoyh111/MeterDetection" ***@***.***&gt;;
抄送："gaoyh111 ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [gaoyh111/MeterDetection] 数据集问题 (Issue #2)
-----------------------------------

 

 
@gaoyh111  您好，我在制作仪表刻度数据集，有一张图片两个仪表，这两个仪表可以标注在一个文件训练还是要把仪表截出来，每一个仪表对应一个单独的标注文件？

**Comment by tanlili2025** [comment]
@gaoyh111 好的，不好意思总是用这种小问题来麻烦您，后面除非和您代码相关的，我都自己解决。
